Added SearchBarView & SearchBar.css components
Break-Glass-If-Replaced-By-ChatGPT/rapid-recruits pull request #14
Opened 2023-03-28 16:04 UTC by jlife24

2023-03-28 16:57 UTC, Damesdev requested changes
Please remove App.js file from the PR can go to files changed and click the 3 dots to delete file.

2023-03-28 16:57 UTC, Damesdev commented on src/App.js
Please remove this from your PR. I have already put in react routing into the main and this will over write it.  Other than that this is fine.

2023-03-28 17:48 UTC, jlife24 commented on src/App.js
just removed it dame.

2023-03-29 01:43 UTC, Damesdev approved these changes

2023-03-29 01:49 UTC, closed without merging